[versions]
paperweight = "2.0.0-beta.19"
protocollib = "5.4.0"
itemsadder = "4.0.10"

[libraries]
protocollib = { module = "net.dmulloy2:ProtocolLib", version.ref = "protocollib" }
itemsadder = { module = "dev.lone:api-itemsadder", version.ref = "itemsadder" }

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }